import {
  Product, Store, Notification, UserProfile,
  ShoppingList, CashbackTransaction, CashbackCoupon,
  MonthlySavings, Achievement, CommunityPost, UserRanking,
  UserBadge, AIRecommendation, EncarteProduct,
} from '@/types';
import { generatePriceHistory } from './utils';

export const mockStores: Store[] = [
  { id: 's1', name: 'Carrefour', logo: '🛒', type: 'mercado', distance: 0.4, rating: 4.3, address: 'Av. Paulista, 1234', cashbackPercent: 2 },
  { id: 's2', name: 'Extra', logo: '🏪', type: 'mercado', distance: 0.8, rating: 4.1, address: 'Rua Augusta, 500', cashbackPercent: 1.5 },
  { id: 's3', name: 'Pão de Açúcar', logo: '🛍️', type: 'mercado', distance: 1.2, rating: 4.5, address: 'Al. Santos, 890', cashbackPercent: 3 },
  { id: 's4', name: 'Droga Raia', logo: '💊', type: 'farmacia', distance: 0.3, rating: 4.4, address: 'Rua Oscar Freire, 210', cashbackPercent: 2.5 },
  { id: 's5', name: 'Ultrafarma', logo: '🏥', type: 'farmacia', distance: 1.5, rating: 4.6, address: 'Av. Rebouças, 3300', cashbackPercent: 4 },
  { id: 's6', name: 'Mercadinho Bom Preço', logo: '🏬', type: 'mercado', distance: 0.2, rating: 3.9, address: 'Rua Fradique, 78', cashbackPercent: 1 },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Coca-Cola 2L',
    image: '🥤',
    category: 'Bebidas',
    originalPrice: 12.99,
    promoPrice: 6.99,
    discount: 46,
    store: mockStores[0],
    unit: 'unidade',
    priceHistory: generatePriceHistory(6.99),
    expiresAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 6.49,
    regionalAvgPrice: 10.5,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 14,
  },
  {
    id: 'p2',
    name: 'Arroz Tio João 5kg',
    image: '🍚',
    category: 'Alimentos',
    originalPrice: 32.9,
    promoPrice: 24.9,
    discount: 24,
    store: mockStores[2],
    unit: 'pacote',
    priceHistory: generatePriceHistory(24.9),
    expiresAt: new Date(Date.now() + 86400000 * 5).toISOString(),
    isFavorite: true,
    alertEnabled: true,
    lowestHistoricalPrice: 23.9,
    regionalAvgPrice: 29.5,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 45,
  },
  {
    id: 'p3',
    name: 'Nescafé Solúvel 500g',
    image: '☕',
    category: 'Bebidas',
    originalPrice: 28.5,
    promoPrice: 19.9,
    discount: 30,
    store: mockStores[1],
    unit: 'pote',
    priceHistory: generatePriceHistory(19.9),
    expiresAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 19.9,
    regionalAvgPrice: 25.0,
    priceStatus: 'lowest',
    purchaseFrequencyDays: 20,
  },
  {
    id: 'p4',
    name: 'Dipirona 500mg 20cp',
    image: '💊',
    category: 'Farmácia',
    originalPrice: 8.9,
    promoPrice: 4.99,
    discount: 44,
    store: mockStores[3],
    unit: 'caixa',
    priceHistory: generatePriceHistory(4.99),
    expiresAt: new Date(Date.now() + 86400000 * 7).toISOString(),
    isFavorite: true,
    alertEnabled: false,
    lowestHistoricalPrice: 4.49,
    regionalAvgPrice: 7.2,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 60,
  },
  {
    id: 'p5',
    name: 'Shampoo Pantene 400ml',
    image: '🧴',
    category: 'Higiene',
    originalPrice: 19.9,
    promoPrice: 13.9,
    discount: 30,
    store: mockStores[4],
    unit: 'frasco',
    priceHistory: generatePriceHistory(13.9),
    expiresAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 12.9,
    regionalAvgPrice: 17.5,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 30,
  },
  {
    id: 'p6',
    name: 'Leite Integral 1L',
    image: '🥛',
    category: 'Laticínios',
    originalPrice: 6.49,
    promoPrice: 4.49,
    discount: 31,
    store: mockStores[5],
    unit: 'caixa',
    priceHistory: generatePriceHistory(4.49),
    expiresAt: new Date(Date.now() + 86400000 * 1).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 4.49,
    regionalAvgPrice: 5.8,
    priceStatus: 'lowest',
    purchaseFrequencyDays: 7,
  },
  {
    id: 'p7',
    name: 'Feijão Carioca 1kg',
    image: '🫘',
    category: 'Alimentos',
    originalPrice: 11.9,
    promoPrice: 7.9,
    discount: 34,
    store: mockStores[0],
    unit: 'pacote',
    priceHistory: generatePriceHistory(7.9),
    expiresAt: new Date(Date.now() + 86400000 * 6).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 7.5,
    regionalAvgPrice: 10.2,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 30,
  },
  {
    id: 'p8',
    name: 'Detergente Ypê 500ml',
    image: '🧹',
    category: 'Limpeza',
    originalPrice: 4.5,
    promoPrice: 2.79,
    discount: 38,
    store: mockStores[1],
    unit: 'frasco',
    priceHistory: generatePriceHistory(2.79),
    expiresAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 2.59,
    regionalAvgPrice: 3.9,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 21,
  },
  {
    id: 'p9',
    name: 'Iogurte Natural 170g',
    image: '🍦',
    category: 'Laticínios',
    originalPrice: 3.99,
    promoPrice: 2.49,
    discount: 38,
    store: mockStores[2],
    unit: 'pote',
    priceHistory: generatePriceHistory(2.49),
    expiresAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 2.29,
    regionalAvgPrice: 3.5,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 7,
  },
  {
    id: 'p10',
    name: 'Sabonete Dove 90g',
    image: '🧼',
    category: 'Higiene',
    originalPrice: 5.99,
    promoPrice: 3.49,
    discount: 42,
    store: mockStores[4],
    unit: 'unidade',
    priceHistory: generatePriceHistory(3.49),
    expiresAt: new Date(Date.now() + 86400000 * 5).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 3.49,
    regionalAvgPrice: 5.0,
    priceStatus: 'lowest',
    purchaseFrequencyDays: 30,
  },
  {
    id: 'p11',
    name: 'Óleo de Soja 900ml',
    image: '🫙',
    category: 'Alimentos',
    originalPrice: 9.9,
    promoPrice: 6.99,
    discount: 29,
    store: mockStores[5],
    unit: 'garrafa',
    priceHistory: generatePriceHistory(6.99),
    expiresAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 6.5,
    regionalAvgPrice: 8.9,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 30,
  },
  {
    id: 'p12',
    name: 'Macarrão Espaguete 500g',
    image: '🍝',
    category: 'Alimentos',
    originalPrice: 5.49,
    promoPrice: 3.29,
    discount: 40,
    store: mockStores[0],
    unit: 'pacote',
    priceHistory: generatePriceHistory(3.29),
    expiresAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    isFavorite: false,
    alertEnabled: false,
    lowestHistoricalPrice: 2.99,
    regionalAvgPrice: 4.8,
    priceStatus: 'below_avg',
    purchaseFrequencyDays: 14,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    productId: 'p1',
    productName: 'Coca-Cola 2L',
    storeName: 'Carrefour',
    oldPrice: 12.99,
    newPrice: 6.99,
    discount: 46,
    distance: 0.4,
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    read: false,
    type: 'price_drop',
    priority: 'high',
  },
  {
    id: 'n2',
    productId: 'p2',
    productName: 'Arroz Tio João 5kg',
    storeName: 'Pão de Açúcar',
    oldPrice: 32.9,
    newPrice: 24.9,
    discount: 24,
    distance: 1.2,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: false,
    type: 'price_drop',
    priority: 'medium',
  },
  {
    id: 'n3',
    productId: 'p3',
    productName: 'Nescafé Solúvel 500g',
    storeName: 'Extra',
    oldPrice: 28.5,
    newPrice: 19.9,
    discount: 30,
    distance: 0.8,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    read: false,
    type: 'ai_suggestion',
    priority: 'high',
  },
  {
    id: 'n4',
    productId: 'p4',
    productName: 'Dipirona 500mg',
    storeName: 'Droga Raia',
    oldPrice: 8.9,
    newPrice: 4.99,
    discount: 44,
    distance: 0.3,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    read: true,
    type: 'price_drop',
    priority: 'medium',
  },
  {
    id: 'n5',
    productId: 'p5',
    productName: 'Shampoo Pantene 400ml',
    storeName: 'Ultrafarma',
    oldPrice: 19.9,
    newPrice: 13.9,
    discount: 30,
    distance: 1.5,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    read: true,
    type: 'price_drop',
    priority: 'low',
  },
  {
    id: 'n6',
    productId: 'p6',
    productName: 'Leite Integral 1L',
    storeName: 'Mercadinho Bom Preço',
    oldPrice: 6.49,
    newPrice: 4.49,
    discount: 31,
    distance: 0.2,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    read: true,
    type: 'expiring_soon',
    priority: 'low',
  },
];

export const mockUserProfile: UserProfile = {
  name: 'Leonardo',
  email: 'leonardo@email.com',
  avatar: '👤',
  location: 'Jardins, São Paulo - SP',
  radius: 3,
  notificationsEnabled: true,
  favoriteCategories: ['Alimentos', 'Bebidas', 'Farmácia'],
  totalSaved: 487.3,
  monthlySavingsGoal: 150,
  points: 2340,
  level: 'Caçador Pro',
};

export const promoBanners = [
  { id: 1, title: 'Promoções de Hoje', subtitle: 'Até 50% OFF em mercados perto de você', color: 'from-violet-600 to-purple-700', emoji: '🛒' },
  { id: 2, title: 'Farmácias em Destaque', subtitle: 'Medicamentos e higiene com desconto', color: 'from-orange-500 to-red-500', emoji: '💊' },
  { id: 3, title: 'Ofertas Relâmpago', subtitle: 'Válidas por apenas 24 horas!', color: 'from-emerald-500 to-teal-600', emoji: '⚡' },
];

// Shopping Lists
export const mockShoppingLists: ShoppingList[] = [
  {
    id: 'l1',
    name: 'Lista Semanal',
    type: 'semanal',
    createdAt: new Date().toISOString(),
    items: [
      { id: 'li1', productId: 'p6', name: 'Leite Integral 1L', quantity: 6, unit: 'cx', estimatedPrice: 4.49, checked: false, category: 'Laticínios', emoji: '🥛' },
      { id: 'li2', productId: 'p9', name: 'Iogurte Natural 170g', quantity: 4, unit: 'pote', estimatedPrice: 2.49, checked: true, category: 'Laticínios', emoji: '🍦' },
      { id: 'li3', productId: 'p1', name: 'Coca-Cola 2L', quantity: 2, unit: 'un', estimatedPrice: 6.99, checked: false, category: 'Bebidas', emoji: '🥤' },
      { id: 'li4', name: 'Pão de Forma', quantity: 1, unit: 'pacote', estimatedPrice: 8.9, checked: false, category: 'Alimentos', emoji: '🍞' },
      { id: 'li5', productId: 'p8', name: 'Detergente Ypê 500ml', quantity: 2, unit: 'fr', estimatedPrice: 2.79, checked: true, category: 'Limpeza', emoji: '🧹' },
      { id: 'li6', name: 'Ovos Caipira 12un', quantity: 1, unit: 'caixa', estimatedPrice: 14.9, checked: false, category: 'Alimentos', emoji: '🥚' },
    ],
  },
  {
    id: 'l2',
    name: 'Lista Mensal',
    type: 'mensal',
    createdAt: new Date().toISOString(),
    items: [
      { id: 'lm1', productId: 'p2', name: 'Arroz Tio João 5kg', quantity: 2, unit: 'pacote', estimatedPrice: 24.9, checked: false, category: 'Alimentos', emoji: '🍚' },
      { id: 'lm2', productId: 'p7', name: 'Feijão Carioca 1kg', quantity: 2, unit: 'pacote', estimatedPrice: 7.9, checked: false, category: 'Alimentos', emoji: '🫘' },
      { id: 'lm3', productId: 'p3', name: 'Nescafé Solúvel 500g', quantity: 1, unit: 'pote', estimatedPrice: 19.9, checked: false, category: 'Bebidas', emoji: '☕' },
      { id: 'lm4', productId: 'p11', name: 'Óleo de Soja 900ml', quantity: 2, unit: 'garrafa', estimatedPrice: 6.99, checked: false, category: 'Alimentos', emoji: '🫙' },
      { id: 'lm5', productId: 'p12', name: 'Macarrão Espaguete 500g', quantity: 3, unit: 'pacote', estimatedPrice: 3.29, checked: false, category: 'Alimentos', emoji: '🍝' },
      { id: 'lm6', productId: 'p5', name: 'Shampoo Pantene 400ml', quantity: 1, unit: 'fr', estimatedPrice: 13.9, checked: false, category: 'Higiene', emoji: '🧴' },
      { id: 'lm7', productId: 'p10', name: 'Sabonete Dove 90g', quantity: 4, unit: 'un', estimatedPrice: 3.49, checked: false, category: 'Higiene', emoji: '🧼' },
      { id: 'lm8', productId: 'p4', name: 'Dipirona 500mg', quantity: 2, unit: 'cx', estimatedPrice: 4.99, checked: false, category: 'Farmácia', emoji: '💊' },
    ],
  },
];

// Cashback
export const mockCashbackBalance = 23.47;

export const mockCashbackTransactions: CashbackTransaction[] = [
  { id: 'cb1', storeName: 'Pão de Açúcar', storeEmoji: '🛍️', amount: 4.8, purchaseValue: 160.0, date: new Date(Date.now() - 86400000 * 2).toISOString(), status: 'confirmed' },
  { id: 'cb2', storeName: 'Droga Raia', storeEmoji: '💊', amount: 2.1, purchaseValue: 84.0, date: new Date(Date.now() - 86400000 * 5).toISOString(), status: 'confirmed' },
  { id: 'cb3', storeName: 'Ultrafarma', storeEmoji: '🏥', amount: 5.6, purchaseValue: 140.0, date: new Date(Date.now() - 86400000 * 8).toISOString(), status: 'confirmed' },
  { id: 'cb4', storeName: 'Carrefour', storeEmoji: '🛒', amount: 3.2, purchaseValue: 160.0, date: new Date(Date.now() - 86400000 * 12).toISOString(), status: 'confirmed' },
  { id: 'cb5', storeName: 'Extra', storeEmoji: '🏪', amount: 1.9, purchaseValue: 126.7, date: new Date(Date.now() - 86400000 * 15).toISOString(), status: 'pending' },
  { id: 'cb6', storeName: 'Carrefour', storeEmoji: '🛒', amount: 5.87, purchaseValue: 293.5, date: new Date(Date.now() - 86400000 * 20).toISOString(), status: 'withdrawn' },
];

export const mockCashbackCoupons: CashbackCoupon[] = [
  { id: 'c1', storeName: 'Carrefour', storeEmoji: '🛒', discount: '10%', description: '10% OFF em Alimentos', expiresAt: new Date(Date.now() + 86400000 * 3).toISOString(), code: 'RADAR10', type: 'percent', minPurchase: 80, color: 'from-violet-500 to-violet-700', used: false },
  { id: 'c2', storeName: 'Droga Raia', storeEmoji: '💊', discount: 'R$ 15', description: 'R$ 15 OFF em compras acima de R$ 60', expiresAt: new Date(Date.now() + 86400000 * 5).toISOString(), code: 'SAUDE15', type: 'fixed', minPurchase: 60, color: 'from-emerald-500 to-teal-600', used: false },
  { id: 'c3', storeName: 'Ultrafarma', storeEmoji: '🏥', discount: '15%', description: '15% OFF em Higiene e Beleza', expiresAt: new Date(Date.now() + 86400000 * 2).toISOString(), code: 'ULTRA15', type: 'percent', minPurchase: 50, color: 'from-blue-500 to-cyan-600', used: false },
  { id: 'c4', storeName: 'Pão de Açúcar', storeEmoji: '🛍️', discount: '8%', description: '8% OFF em Laticínios e Frios', expiresAt: new Date(Date.now() + 86400000 * 7).toISOString(), code: 'LATIC8', type: 'percent', minPurchase: 40, color: 'from-orange-500 to-amber-600', used: false },
  { id: 'c5', storeName: 'Extra', storeEmoji: '🏪', discount: 'R$ 20', description: 'R$ 20 OFF na primeira compra', expiresAt: new Date(Date.now() + 86400000 * 10).toISOString(), code: 'PRIMEIRACOMP', type: 'fixed', minPurchase: 100, color: 'from-pink-500 to-rose-600', used: false },
  { id: 'c6', storeName: 'Mercadinho Bom Preço', storeEmoji: '🏬', discount: '5%', description: '5% OFF em qualquer compra', expiresAt: new Date(Date.now() + 86400000 * 1).toISOString(), code: 'BOM5', type: 'percent', color: 'from-slate-500 to-slate-700', used: false },
];

// Monthly Savings
export const mockMonthlySavings: MonthlySavings[] = [
  { month: 'Dezembro', shortMonth: 'Dez', year: 2024, saved: 89.3, purchases: 8 },
  { month: 'Janeiro', shortMonth: 'Jan', year: 2025, saved: 112.5, purchases: 11 },
  { month: 'Fevereiro', shortMonth: 'Fev', year: 2025, saved: 78.9, purchases: 7 },
  { month: 'Março', shortMonth: 'Mar', year: 2025, saved: 134.2, purchases: 13 },
  { month: 'Abril', shortMonth: 'Abr', year: 2025, saved: 98.7, purchases: 9 },
  { month: 'Maio', shortMonth: 'Mai', year: 2025, saved: 127.4, purchases: 12 },
];

// Achievements
export const mockAchievements: Achievement[] = [
  { id: 'a1', title: 'Primeira Economia', description: 'Economizou pela primeira vez', emoji: '🏆', unlocked: true, unlockedAt: '2025-01-15', rarity: 'common' },
  { id: 'a2', title: 'Caçador de Promoções', description: 'Aproveitou 10 promoções', emoji: '🎯', unlocked: true, unlockedAt: '2025-02-03', rarity: 'common' },
  { id: 'a3', title: 'Mestre da Economia', description: 'Economizou R$ 500 no total', emoji: '💰', unlocked: false, progress: 487, maxProgress: 500, rarity: 'rare' },
  { id: 'a4', title: 'Top Contribuidor', description: 'Enviou 5 promoções verificadas', emoji: '⭐', unlocked: true, unlockedAt: '2025-03-10', rarity: 'rare' },
  { id: 'a5', title: 'Radar Ativo', description: 'Usou o app por 30 dias consecutivos', emoji: '📡', unlocked: false, progress: 21, maxProgress: 30, rarity: 'epic' },
  { id: 'a6', title: 'Lista Inteligente', description: 'Otimizou 5 listas de compras', emoji: '🛒', unlocked: false, progress: 3, maxProgress: 5, rarity: 'common' },
  { id: 'a7', title: 'Lenda das Promoções', description: 'Economizou R$ 1.000 no total', emoji: '👑', unlocked: false, progress: 487, maxProgress: 1000, rarity: 'legendary' },
  { id: 'a8', title: 'Cashback Expert', description: 'Resgatou R$ 50 em cashback', emoji: '💳', unlocked: false, progress: 23, maxProgress: 50, rarity: 'rare' },
];

// Community
export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'cp1', userName: 'Ana Silva', userAvatar: '👩', userLevel: 'Caçadora Pro',
    storeName: 'Carrefour Paulista', storeEmoji: '🛒',
    productName: 'Café Pelé 500g', productEmoji: '☕',
    price: 15.9, originalPrice: 28.9, discount: 45,
    votes: 47, userVoted: false, comments: 8, neighborhood: 'Bela Vista',
    timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(), verified: true,
  },
  {
    id: 'cp2', userName: 'Carlos Mendes', userAvatar: '👨', userLevel: 'Economizador',
    storeName: 'Droga Raia Oscar Freire', storeEmoji: '💊',
    productName: 'Omeprazol 20mg 28cp', productEmoji: '💊',
    price: 12.99, originalPrice: 24.9, discount: 48,
    votes: 32, userVoted: true, comments: 5, neighborhood: 'Jardins',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), verified: true,
  },
  {
    id: 'cp3', userName: 'Mariana Costa', userAvatar: '👩‍🦰', userLevel: 'Iniciante',
    storeName: 'Pão de Açúcar Santos', storeEmoji: '🛍️',
    productName: 'Manteiga Aviação 200g', productEmoji: '🧈',
    price: 7.49, originalPrice: 14.9, discount: 50,
    votes: 89, userVoted: false, comments: 14, neighborhood: 'Cerqueira César',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(), verified: true,
  },
  {
    id: 'cp4', userName: 'Pedro Alves', userAvatar: '👨‍💼', userLevel: 'Caçador Pro',
    storeName: 'Extra Augusta', storeEmoji: '🏪',
    productName: 'Coca-Cola 2L (cx 6un)', productEmoji: '🥤',
    price: 34.9, originalPrice: 58.9, discount: 41,
    votes: 56, userVoted: false, comments: 11, neighborhood: 'Consolação',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(), verified: false,
  },
  {
    id: 'cp5', userName: 'Julia Santos', userAvatar: '👩‍🎓', userLevel: 'Top Economista',
    storeName: 'Ultrafarma Rebouças', storeEmoji: '🏥',
    productName: 'Whey Protein 900g', productEmoji: '💪',
    price: 89.9, originalPrice: 149.9, discount: 40,
    votes: 124, userVoted: false, comments: 22, neighborhood: 'Pinheiros',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(), verified: true,
  },
];

export const mockUserRankings: UserRanking[] = [
  { position: 1, name: 'Julia Santos', avatar: '👩‍🎓', points: 8920, level: 'Top Economista', badge: '👑', promotionsSubmitted: 124 },
  { position: 2, name: 'Pedro Alves', avatar: '👨‍💼', points: 6540, level: 'Lenda', badge: '🏆', promotionsSubmitted: 89 },
  { position: 3, name: 'Ana Silva', avatar: '👩', points: 5230, level: 'Caçadora Pro', badge: '🎯', promotionsSubmitted: 67 },
  { position: 4, name: 'Carlos Mendes', avatar: '👨', points: 3870, level: 'Economizador', badge: '⭐', promotionsSubmitted: 45 },
  { position: 5, name: 'Mariana Costa', avatar: '👩‍🦰', points: 2890, level: 'Explorador', badge: '🔍', promotionsSubmitted: 34 },
  { position: 8, name: 'Leonardo', avatar: '👤', points: 2340, level: 'Caçador Pro', badge: '🎯', promotionsSubmitted: 21, isCurrentUser: true },
];

export const mockUserBadges: UserBadge[] = [
  { id: 'b1', title: 'Caçador de Promoções', emoji: '🎯', description: 'Enviou promoções verificadas', unlocked: true, rarity: 'common' },
  { id: 'b2', title: 'Top Economista', emoji: '💰', description: 'Economizou mais de R$ 300', unlocked: true, rarity: 'rare' },
  { id: 'b3', title: 'Radar Ativo', emoji: '📡', description: '30 dias consecutivos no app', unlocked: false, rarity: 'epic' },
  { id: 'b4', title: 'Lenda das Promoções', emoji: '👑', description: 'Top 3 no ranking geral', unlocked: false, rarity: 'legendary' },
  { id: 'b5', title: 'Primeiro Cashback', emoji: '💳', description: 'Resgatou cashback pela 1ª vez', unlocked: true, rarity: 'common' },
  { id: 'b6', title: 'Mestre da Lista', emoji: '📋', description: 'Otimizou 10 listas', unlocked: false, rarity: 'rare' },
];

// AI Recommendations
export const mockAIRecommendations: AIRecommendation[] = [
  {
    product: mockProducts[2],
    reason: 'Você costuma comprar a cada 20 dias',
    badge: 'menor_preco',
    badgeLabel: 'Menor preço',
  },
  {
    product: mockProducts[5],
    reason: 'Você vai precisar em ~3 dias',
    badge: 'proximo_comprar',
    badgeLabel: 'Comprar logo',
  },
  {
    product: mockProducts[1],
    reason: 'Seu favorito caiu 24%',
    badge: 'favorito_caiu',
    badgeLabel: 'Favorito',
  },
  {
    product: mockProducts[0],
    reason: 'Oferta relâmpago — 2 dias',
    badge: 'quase_acabando',
    badgeLabel: 'Acaba logo',
  },
];

// OCR Encarte mock results
export const mockEncarteProducts: EncarteProduct[] = [
  { name: 'Arroz Tio João 5kg', emoji: '🍚', price: 22.9, originalPrice: 32.9, discount: 30, validUntil: 'Válido até 12/05' },
  { name: 'Feijão Carioca 1kg', emoji: '🫘', price: 6.99, originalPrice: 11.9, discount: 41, validUntil: 'Válido até 10/05' },
  { name: 'Óleo de Soja 900ml', emoji: '🫙', price: 5.99, originalPrice: 9.9, discount: 39, validUntil: 'Válido até 15/05' },
  { name: 'Açúcar União 2kg', emoji: '🍬', price: 7.9, originalPrice: 11.9, discount: 34, validUntil: 'Válido até 12/05' },
  { name: 'Macarrão Espaguete 500g', emoji: '🍝', price: 2.49, originalPrice: 5.49, discount: 55, validUntil: 'Válido até 10/05' },
  { name: 'Leite Integral 1L', emoji: '🥛', price: 3.99, originalPrice: 6.49, discount: 38, validUntil: 'Válido até 08/05' },
];
